import express from 'express';
import cors from 'cors';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url));
const file=join(here,'data.json');
const app=express();app.use(cors());app.use(express.json({limit:'32kb'}));
const statuses=['Aberto','Em andamento','Resolvido'];const priorities=['Baixa','Média','Alta','Crítica'];
const today=Date.now();const seed=[
['Configurar acesso à VPN','Acesso','Alta','Em andamento','Marcos','Ana Oliveira',1],['Notebook não inicia','Hardware','Crítica','Aberto','Marcos','Carlos Silva',2],['Instalação de software','Software','Média','Resolvido','Julia Santos','Fernanda Lima',3],['Erro no acesso ao e-mail','Acesso','Alta','Aberto','Marcos','Pedro Rocha',4],['Lentidão na rede Wi-Fi','Redes','Média','Em andamento','Lucas Costa','Beatriz Souza',5],['Atualizar estações Windows','Infraestrutura','Baixa','Resolvido','Julia Santos','Rafael Alves',6],['Impressora fora da rede','Hardware','Baixa','Aberto','Marcos','Mariana Reis',0],['Permissão em pasta compartilhada','Acesso','Média','Resolvido','Lucas Costa','Diego Martins',2]
].map(([title,category,priority,status,assignee,requester,days],i)=>({id:`DF-${String(i+1001)}`,title,description:`Solicitação de demonstração: ${title}.`,category,priority,status,assignee,requester,createdAt:new Date(today-Number(days)*86400000).toISOString(),updatedAt:new Date(today-Number(days)*86400000).toISOString()}));
let queue=Promise.resolve();async function read(){try{return JSON.parse(await readFile(file,'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;await mkdir(dirname(file),{recursive:true});await writeFile(file,JSON.stringify(seed,null,2));return seed;}}
async function mutate(fn){const job=queue.then(async()=>{const items=await read();const result=fn(items);await writeFile(file,JSON.stringify(items,null,2));return result;});queue=job.then(()=>{},()=>{});return job;}
const valid=(v,partial=false)=>{if(!v||typeof v!=='object'||Array.isArray(v))return 'Corpo JSON inválido';if(!partial&&(!v.title||!v.requester))return 'Título e solicitante são obrigatórios';if(v.title!==undefined&&(typeof v.title!=='string'||v.title.trim().length<4||v.title.length>120))return 'Título deve ter entre 4 e 120 caracteres';if(v.requester!==undefined&&(typeof v.requester!=='string'||!v.requester.trim()||v.requester.length>100))return 'Solicitante inválido';if(v.description!==undefined&&(typeof v.description!=='string'||v.description.length>2000))return 'Descrição inválida';if(v.status!==undefined&&!statuses.includes(v.status))return 'Status inválido';if(v.priority!==undefined&&!priorities.includes(v.priority))return 'Prioridade inválida';for(const key of ['category','assignee'])if(v[key]!==undefined&&(typeof v[key]!=='string'||v[key].length>100))return `${key} inválido`;return null;};
const fields=['title','description','category','priority','status','assignee','requester'];const pick=v=>Object.fromEntries(fields.filter(k=>v[k]!==undefined).map(k=>[k,typeof v[k]==='string'?v[k].trim():v[k]]));
app.get('/api/health',(_req,res)=>res.json({status:'ok',service:'deskflow-api'}));
app.get('/api/tickets',async(_req,res,next)=>{try{res.json((await read()).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)));}catch(e){next(e);}});
app.get('/api/tickets/:id',async(req,res,next)=>{try{const ticket=(await read()).find(t=>t.id===req.params.id);if(!ticket)return res.status(404).json({error:'Chamado não encontrado'});res.json(ticket);}catch(e){next(e);}});
app.post('/api/tickets',async(req,res,next)=>{const err=valid(req.body);if(err)return res.status(400).json({error:err});try{const ticket=await mutate(items=>{const next=Math.max(1000,...items.map(t=>Number(t.id.replace('DF-',''))||1000))+1;const now=new Date().toISOString();const ticket={id:`DF-${next}`,description:'',category:'Outros',priority:'Média',status:'Aberto',assignee:'',...pick(req.body),createdAt:now,updatedAt:now};items.push(ticket);return ticket;});res.status(201).json(ticket);}catch(e){next(e);}});
app.patch('/api/tickets/:id',async(req,res,next)=>{const err=valid(req.body,true);if(err)return res.status(400).json({error:err});try{const ticket=await mutate(items=>{const t=items.find(x=>x.id===req.params.id);if(!t)return null;Object.assign(t,pick(req.body),{updatedAt:new Date().toISOString()});return t;});if(!ticket)return res.status(404).json({error:'Chamado não encontrado'});res.json(ticket);}catch(e){next(e);}});
app.delete('/api/tickets/:id',async(req,res,next)=>{try{const removed=await mutate(items=>{const i=items.findIndex(t=>t.id===req.params.id);if(i<0)return false;items.splice(i,1);return true;});if(!removed)return res.status(404).json({error:'Chamado não encontrado'});res.json({ok:true});}catch(e){next(e);}});
app.use((err,_req,res,_next)=>{console.error(err);res.status(err.status||500).json({error:err.status===400?'JSON inválido':'Erro interno do servidor'});});
const port=Number(process.env.PORT)||3001;app.listen(port,()=>console.log(`DeskFlow API disponível em http://localhost:${port}`));
