import {useEffect,useState} from 'react';
import {X,Save} from 'lucide-react';
import type {Ticket,TicketInput,Priority,TicketStatus} from '../lib/types';
import {priorities,statusList} from '../lib/utils';
const empty:TicketInput={title:'',description:'',category:'Hardware',priority:'Média',status:'Aberto',assignee:'Marcos',requester:''};
type Props={ticket?:Ticket|null;busy:boolean;onClose:()=>void;onSave:(data:TicketInput)=>Promise<void>};
const inputClass='w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100';
export function TicketForm({ticket,busy,onClose,onSave}:Props){const [form,setForm]=useState<TicketInput>(empty);const [error,setError]=useState('');useEffect(()=>{setForm(ticket?{title:ticket.title,description:ticket.description,category:ticket.category,priority:ticket.priority,status:ticket.status,assignee:ticket.assignee,requester:ticket.requester}:empty);setError('');},[ticket]);function set<K extends keyof TicketInput>(key:K,value:TicketInput[K]){setForm(f=>({...f,[key]:value}));}async function submit(e:React.FormEvent){e.preventDefault();if(form.title.trim().length<4||!form.requester.trim()){setError('Informe um título com pelo menos 4 caracteres e o solicitante.');return;}setError('');await onSave({...form,title:form.title.trim(),requester:form.requester.trim()});}
return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div role="dialog" aria-modal="true" aria-labelledby="modal-title" className="w-full max-w-xl max-h-[92vh] overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-100 p-6"><div><h2 id="modal-title" className="text-xl font-bold">{ticket?'Editar chamado':'Novo chamado'}</h2><p className="mt-1 text-sm text-slate-500">Preencha os dados do atendimento</p></div><button aria-label="Fechar" onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X size={20}/></button></div><form onSubmit={submit} className="space-y-4 p-6"><label className="block text-sm font-medium">Título *<input className={`${inputClass} mt-1.5`} value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Ex.: Computador não conecta à rede" maxLength={120}/></label><label className="block text-sm font-medium">Descrição<textarea className={`${inputClass} mt-1.5 min-h-24`} value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Descreva o problema..." maxLength={2000}/></label><div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Solicitante *<input className={`${inputClass} mt-1.5`} value={form.requester} onChange={e=>set('requester',e.target.value)} placeholder="Nome do solicitante"/></label><label className="block text-sm font-medium">Responsável<input className={`${inputClass} mt-1.5`} value={form.assignee} onChange={e=>set('assignee',e.target.value)}/></label><label className="block text-sm font-medium">Categoria<select className={`${inputClass} mt-1.5`} value={form.category} onChange={e=>set('category',e.target.value)}>{['Hardware','Software','Redes','Acesso','Infraestrutura','Outros'].map(c=><option key={c}>{c}</option>)}</select></label><label className="block text-sm font-medium">Prioridade<select className={`${inputClass} mt-1.5`} value={form.priority} onChange={e=>set('priority',e.target.value as Priority)}>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label className="block text-sm font-medium sm:col-span-2">Status<select className={`${inputClass} mt-1.5`} value={form.status} onChange={e=>set('status',e.target.value as TicketStatus)}>{statusList.map(s=><option key={s}>{s}</option>)}</select></label></div>{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}<div className="flex justify-end gap-3 pt-3"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-semibold hover:bg-slate-50">Cancelar</button><button disabled={busy} type="submit" className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700"><Save size={16}/>{busy?'Salvando...':'Salvar chamado'}</button></div></form></div></div>}
